### PR TITLE
[ci] survive the new runner images: use the image podman, smoke-probe the stack at setup

### PR DESCRIPTION
**Pull request by DamianReeves**
Fixes the linux CI failures tracked in #1881.

## What broke

The 20260810.x runner images (rolled out gradually from Aug 12) ship podman 5.8.4 under `/usr/local` with matching helpers (conmon, netavark) in `/usr/local/lib/podman`. Our setup action still apt-installed Ubuntu's podman 4.9.3 on top of it. The package's `containers.conf` selects the journald log driver, the image's conmon is built without journald support, so conmon exits 1 on every container start. The container never leaves the `created` state and each exec fails with HTTP 500 `container state improper`, which took down all `[podman]` cases of the kyo-pod suites on JVM, JS, Native, and Wasm, on both x64 and arm64.

A probe matrix on the new images (see #1881) confirmed: the image's own podman stack passes a create + start + exec cycle with crun, runc, and the default runtime on both architectures, while any mix with the apt package fails with the exact CI error.

## The fix

- Use the podman the runner image ships when there is one, and apt-install podman only when the image provides none, so each stack stays coherent on its own.
- Add a health gate right after the podman API service comes up. A broken container stack now fails the setup step with a named cause instead of surfacing two hours later inside the kyo-pod suites.
- The runc pin stays where it was and stays unconditional: the probe verified the image podman works pinned to runc on both architectures, so there is no need to branch on where podman came from.

## Approach: logic in scripts, workflows stay declarative

The first version of this branch put both the install conditionals and the health checks inline in the setup action, which hurt the readability of the workflow. Both now live in scripts, and each script carries a flag that changes policy without restructuring the workflow.

**`scripts/apt-install.sh --if-missing`** expresses "install unless present". The callers read as plain one-liners:

```sh
bash scripts/apt-install.sh --if-missing podman uidmap
bash scripts/apt-install.sh --if-missing cmake go:golang-go liburing-dev
```

It skips a package when dpkg reports it installed, or when a binary with its name is already on PATH. The PATH check is the piece that matters for #1881: it is what keeps the image's `/usr/local` podman in place instead of layering the apt package on top of it. When the command name differs from the package name, a `cmd:pkg` token maps one to the other (`go:golang-go`: the runners ship go as a tarball, so neither dpkg nor a `golang-go` lookup would find it). When nothing is missing the script exits without touching apt, which also saves the `apt-get update` round-trip. The same flag replaces every inline `command -v X || apt-install` and `dpkg -s X || apt-install` guard that had accumulated across `release.yml`, `deploy-site.yml`, `readme.yml`, `release-setup/action.yml`, and the libaeron step of the setup action, so the repo now has one idiom for "install unless present" instead of three.

**`scripts/container-check.sh`** is the health gate. It verifies both runtimes the kyo-pod suites depend on: the full podman cycle (create, start, exec a real container, after printing the resolved OCI runtime and conmon so a failure names the component) and the docker daemon. Both checks always run, so one broken runtime does not hide the state of the other. The workflow calls it as a single line:

```sh
bash scripts/container-check.sh
```

By default a failed check fails the job. `--warn-only` runs the same checks and diagnostics but emits a GitHub warning annotation and exits 0: the switch for maintainers who later decide the gate should be loud instead of fatal, one flag in the workflow instead of a rewrite of the step.

### CODE REVIEW

**Comment by DamianReeves** [comment]
The linux-x64 JVM job hit a transient NoClassDefFoundError in kyo-net (IoUringDriverAcceptTransientErrnoTest) on both runs of this branch. It is unrelated to the podman work here: the classfile exists, the suite passes in isolation (8 probe runs), fd and memory are healthy at the failure moment, and the same suite passed on main on the same runner image. Full evidence dossier and open directions are in #1884. I will rerun the failed job once the current run completes.

**Comment by DamianReeves** [comment]
Run 31894626796 update: the kyo-pod suites now pass everywhere they run, so both podman 5.8.4 fixes hold (image podman selection and the PidsLimit omission). The two JVM job failures in this run are distinct pre-existing races that the recently added end-of-run checks surface: the kyo-net classload flake (#1884, linux-x64) and a kyo-sql leaked client connection (#1885, linux-arm64). Both are tracked with full evidence; neither is caused by this branch. I will rerun the failed jobs when the run completes.

**Comment by DamianReeves** [comment]
CI is fully green: all eight build jobs pass, including the kyo-pod container suites on every platform and architecture. The two JVM job failures along the way were the pre-existing races tracked in #1884 and #1885, not this branch; #1885 is now precisely diagnosed (the pool's exit decision never runs when an externally interrupted fiber is parked on a socket read) with an on-demand reproduction kept on the ci/podman-runner-image-probe branch. Ready for review.
